FROM node:20.10.0-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

ARG NEXT_PUBLIC_API_URI
ARG NEXT_PUBLIC_API_GRAPHQL_URL
ARG NEXT_PUBLIC_API_WS
ARG NEXT_PUBLIC_WS_URL

ENV NEXT_PUBLIC_API_URI=$NEXT_PUBLIC_API_URI
ENV NEXT_PUBLIC_API_GRAPHQL_URL=$NEXT_PUBLIC_API_GRAPHQL_URL
ENV NEXT_PUBLIC_API_WS=$NEXT_PUBLIC_API_WS
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

RUN pnpm run build

EXPOSE 3000
CMD ["pnpm", "run", "start"]